SUBROUTINE SELECT


# C         NSELT=2  CHOOSE INITIAL CONDITIONS FOR ONE OR TWO MOLECULES
# C
# C         IN THE MAIN PROGRAM THE COORDINATES Q ARE SET EQUAL TO QZ
# C         AND THE MOMENTA P ARE SET EQUAL TO ZERO (FOR NSELT=2).
# C
# C         INITIAL CONDITIONS FOR REACTANT A

#-->IN THIS CASE, ONLY REACTANT A IS MOVING, SURFACE IS FIXED AS REACTANT B 
   J=NATOMA(1)
   DO I=1,J
      K3=3*I
      Q(K3)=QZA(1,K3)+ZASYM
   ENDDO
#  ENERGY REFERENCE FOR SEPARATED REACTANTS
CALL ENERGY

DH=V

# C             SELECT INITIAL Q'S AND P'S FOR REACTANT A
L(1)=LA(1,1)
L(2)=LA(1,2)
# C          DIATOM A IS TREATED SEMICLASSICALLY
IF (NSFLAG.NE.1) THEN
   IF(NTZ.EQ.1)THEN
    N=NATOMA(1
    WRITE(26,*) 'NORMAL MODES FOR FRAGMENT A IN PATH ',1
    WRITE(26,*)
    CALL NMODE(N,0) 
    DUM=EIG(6)
   ENDIF

   IF(TRVA.GE.0.0D0) THEN

      IF (NACTA.EQ.0) THEN
!!!   adapted by Bin, 2016/10/10, for maxwell-boltzmann sampling
      DESKET=SQRT(0.00198717D0*TRVA*C1) 
      WT=WTA(1)
      DO I = 1,NATOMA(1)
         J3=3*LA(1,I)
         J2=J3-1
         J1=J2-1
         J=LA(1,I)
         P(J1)=GASDEV(ISEED)*DESKET*SQRT(W(J))
         P(J2)=GASDEV(ISEED)*DESKET*SQRT(W(J))
         P(J3)=GASDEV(ISEED)*DESKET*SQRT(W(J))
      ENDDO

      CALL CENMAS(WT,QCM,VCM,NATOMA(1))
      DO I=1,NATOMA(1)
         J=3*LA(1,I)
         DO K=0,2
            Q(J-K)=QQ(J-K)      !Coordinates shifted to center of mass frame
            PP(J-K)=P(J-K)      !This is important because we actually do not want to remove the center of mass velocity
         ENDDO
      ENDDO

      CALL ROTATE(NATOMA(1))

!!!   remove velocities along z axis which are replaced by the
!translational energy given later 
      DO I=1,NATOMA(1)
         J=3*LA(1,I)
         P(J)=0D0
         PP(J)=0D0
      ENDDO

      GOTO 126

      ENDIF

     WRITE(6,*)'N AND J CHOSEN BASED ON TEMPERATURE'
     WRITE(6,*) 'TRVA = ',TRVA
# C          CALCULATE N
     IF(NTZ.EQ.1)THEN
      WWA(1)=EIG(6)*C6
      WWASTORE=WWA(1)
     ELSE
      WWA(1)=WWASTORE
      DUM=WWA(1)/C6  
     ENDIF
     NMBAR=1

     CALL THRMAN(WWA,ANNA,TRVA,NMBAR)
     NNA=NINT(ANNA)

     WRITE(6,*) 'NNA = ',NNA
# C          CALCULATE J
     WD1=W(L(1))
     WD2=W(L(2))
     CALL PROBJ(TROTA,AIA,ISEED,JA)
     WRITE(6,*) 'JA = ',JA
   ELSE
     WRITE(6,*) 'N AND J USED AS INPUT'
   ENDIF

   ENJA=(DBLE(NNA)+0.5D0)*DUM*CM2CAL*C1
   CALL INITEBK(NNA,JA,RMINA,RMAXA,DH,RMASSA,ENJA,PTESTA,ALA)
   SDUM=ENJA/C1
   WRITE(6,100)DUM,SDUM
ENDIF
# C             SELECT INITIAL RELATIVE COORDINATE AND MOMENTUM.
DUM=ALA**2/2.0D0/RMASSA
102 RAND=RAND0(ISEED)
R=RMINA+(RMAXA-RMINA)*RAND
Q(3*L(1))=-0.5D0*R
Q(3*L(1)-1)=0.0D0
Q(3*L(1)-2)=0.0D0
Q(3*L(2))= 0.5D0*R
Q(3*L(2)-1)=0.0D0
Q(3*L(2)-2)=0.0D0
# !-->    SHIFT Z COORINDATES UP IN ORDER TO CALCULATE THE POTENTIAL ENERGY
IF (NSURF>0) THEN
   J=NATOMA(1)
   DO I=1,J
      K3=3*I
      Q(K3)=Q(K3)+ZASYM
   ENDDO
ENDIF


CALL ENERGY
# !-->    SHIFT Z COORINDATES BACK AFTER THE POTENTIAL ENERGY
IF (NSURF.GT.0) THEN
J=NATOMA(1)
DO I=1,J
   K3=3*I
   Q(K3)=Q(K3)-ZASYM
ENDDO
ENDIF

VDUM=(V-DH)*C1
SUMM=ENJA-DUM/R**2-VDUM
IF (SUMM<=0.0) THEN
   SUMM=0.0D0
   PR=0.0D0
ELSE
   PR=SQRT(2.0D0*RMASSA*SUMM)
   SDUM=PTESTA/PR
   RAND=RAND0(ISEED)
   IF (SDUM.LT.RAND) GOTO 102
ENDIF
RAND=RAND0(ISEED)
IF (RAND<0.5) PR=-PR
# C             CHOOSE INITIAL CARTESIAN COORDINATES AND MOMENTA, AND
# C             ANGULAR MOMENTUM.  DIATOM LIES ALONG THE X-AXIS.
# C             THEN RANDOMLY ROTATE THE CARTESIAN COORDINATES AND
# C             MOMENTA IN THE CENTER OF MASS FRAME.
CALL HOMOQP(R,PR,ALA,AMA,RMASSA,AI)
AMAI(1)=AMA(1)/ħ
AMAI(2)=AMA(2)/ħ
AMAI(3)=AMA(3)/ħ
AMAI(4)=AMA(4)/ħ
CALL ROTN(AMA,EROTA,2)
WRITE(6,106)AMAI(1),AMAI(2),AMAI(3)




