SUBROUTINE SELECT
# C         NSELT=2  CHOOSE INITIAL CONDITIONS FOR ONE OR TWO MOLECULES
# C         IN THE MAIN PROGRAM THE COORDINATES Q ARE SET EQUAL TO QZ
# C         AND THE MOMENTA P ARE SET EQUAL TO ZERO (FOR NSELT=2).

#-->IN THIS CASE, ONLY REACTANT A IS MOVING, SURFACE IS FIXED AS REACTANT B 
   J=NATOMA(1)
   DO I=1,J
      K3=3*I
      Q(K3)=QZA(1,K3)+ZASYM
   ENDDO
#  ENERGY REFERENCE FOR SEPARATED REACTANTS
CALL ENERGY

DH=V

# C             SELECT INITIAL Q'S AND P'S FOR REACTANT A
L(1)=LA(1,1)
L(2)=LA(1,2)
# C          DIATOM A IS TREATED SEMICLASSICALLY
if (NSFLAG!=1)
    ENJA=(DBLE(NNA)+0.5)*DUM
    CALL INITEBK(NNA,JA,RMIN,RMAX,DH,RMASSA,ENJA,PTESTA,ALA)  #Gives RMIN and RMAX
    SDUM=ENJA
    WRITE(6,100)DUM,SDUM
end

# SELECT INITIAL RELATIVE COORDINATE AND MOMENTUM.
DUM=ALA**2/2.0/RMASSA
102 RAND=RAND0(ISEED)
R=RMIN+(RMAX-RMIN)*RAND
Q(3*L(1))=-0.5*R
Q(3*L(1)-1)=0.0
Q(3*L(1)-2)=0.0
Q(3*L(2))= 0.5*R
Q(3*L(2)-1)=0.0
Q(3*L(2)-2)=0.0

# !-->    SHIFT Z COORINDATES UP IN ORDER TO CALCULATE THE POTENTIAL ENERGY
J=NATOMA(1)
DO I=1,J
    K3=3*I
    Q(K3)=Q(K3)+ZASYM
ENDDO
CALL ENERGY
# !-->    SHIFT Z COORINDATES BACK AFTER THE POTENTIAL ENERGY
J=NATOMA(1)
DO I=1,J
   K3=3*I
   Q(K3)=Q(K3)-ZASYM
ENDDO

VDUM=(V-DH)
SUMM=ENJA-DUM/R**2-VDUM
if (SUMM<=0.0)
   SUMM=0.0
   PR=0.0
else
   PR=sqrt(2.0*RMASSA*SUMM)
   SDUM=PTESTA/PR
   RAND=RAND0(ISEED)
   IF (SDUM.LT.RAND) GOTO 102
end
RAND=RAND0(ISEED)
IF (RAND<0.5) PR=-PR
# CHOOSE INITIAL CARTESIAN COORDINATES AND MOMENTA, AND
# ANGULAR MOMENTUM.  DIATOM LIES ALONG THE X-AXIS.
# THEN RANDOMLY ROTATE THE CARTESIAN COORDINATES AND
# MOMENTA IN THE CENTER OF MASS FRAME.
CALL HOMOQP(R,PR,ALA,AMA,RMASSA,AI)
AMAI(1)=AMA(1)/ħ
AMAI(2)=AMA(2)/ħ
AMAI(3)=AMA(3)/ħ
AMAI(4)=AMA(4)/ħ
CALL ROTN(AMA,EROTA,2)
WRITE(6,106)AMAI(1),AMAI(2),AMAI(3)




