function find_height()
    #DUMX,DUMY,DUMZ ARE THE COORDINATE OF A UNIT VECTOR ORTHOGONAL
    #TO THE SURFACE PLANE THAT HAS BEEN DEFINED BY THE USER
    
    O[1]=R[3*NN2-2]-R[3*NN1-2)
    O[2]=R[3*NN2-1]-R[3*NN1-1)
    O[3]=R[3*NN2]-R[3*NN1)
    O2[1]=R[3*NN3-2]-R[3*NN1-2)
    O2[2]=R[3*NN3-1]-R[3*NN1-1)
    O2[3]=R[3*NN3]-R[3*NN1)
    
    DUMX=O[2]*O2[3]-O[3]*O2[2]
    DUMY=O2[1]*O[3]-O[1]*O2[3]
    DUMZ=O[1]*O2[2]-O[2]*O2[1]
    PNORM=SQRT(DUMX*DUMX+DUMY*DUMY+DUMZ*DUMZ)
    DUMX=DUMX/PNORM
    DUMY=DUMY/PNORM
    DUMZ=DUMZ/PNORM
    NC0=NC
    NTZ0=NTZ

   #POSITION HEIGHT ABOVE THE SURFACE PLANE

    DUMIX=R[3*IHT-2]-R[3*NN1-2)
    DUMIY=R[3*IHT-1]-R[3*NN1-1)
    DUMIZ=R[3*IHT]-R[3*NN1)
    HT=DUMX*DUMIX+DUMY*DUMIY+DUMZ*DUMIZ

    return HT
end