name: CompatHelper
on:
  schedule:
    - cron: 0 0 * * *
  workflow_dispatch:
jobs:
  CompatHelper:
    runs-on: ubuntu-latest
    steps:
      - name: "Install CompatHelper"
        run: |
          import Pkg
          name = "CompatHelper"
          uuid = "aa819f21-2bde-4658-8897-bab36330d9b7"
          version = "2"
          Pkg.add(; name, uuid, version)
        shell: julia --color=yes {0}

      - name: "Run CompatHelper"
        run: |
          import Pkg
          import CompatHelper
          registries = [
            Pkg.RegistrySpec(name = "General",
                             uuid = "23338594-aafe-5451-b93e-139f81909106",
                             url = "https://github.com/JuliaRegistries/General.git"),
            Pkg.RegistrySpec(name = "NQCDRegistry",
                             uuid = "7990252a-03d5-40b3-a380-28ea39a0ee77",
                             url = "https://github.com/NQCD/NQCDRegistry"),
            Pkg.RegistrySpec(name = "MolSim",
                             uuid = "32ac3b6c-ffe8-11e9-1ee5-675a63b9b27b",
                             url = "https://github.com/JuliaMolSim/MolSim.git")
          ]
          CompatHelper.main(;registries=registries)
        shell: julia --color=yes {0}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COMPATHELPER_PRIV: ${{ secrets.DOCUMENTER_KEY }}
